// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQ4zutajxiVHKwq1tUzP01zlK4lzJ6LE',
    appId: '1:692445282265:web:34041e7908515eee4f63c8',
    messagingSenderId: '692445282265',
    projectId: 'caramel-caster-466105-n4',
    authDomain: 'caramel-caster-466105-n4.firebaseapp.com',
    databaseURL: 'https://caramel-caster-466105-n4-default-rtdb.firebaseio.com',
    storageBucket: 'caramel-caster-466105-n4.firebasestorage.app',
    measurementId: 'G-ZRW3QFWKRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLvdFLrrAwqbGVw9M_ZSWlHD_7BtQkYk',
    appId: '1:692445282265:android:4a60fdc13ac71f144f63c8',
    messagingSenderId: '692445282265',
    projectId: 'caramel-caster-466105-n4',
    databaseURL: 'https://caramel-caster-466105-n4-default-rtdb.firebaseio.com',
    storageBucket: 'caramel-caster-466105-n4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjgHFZiLSIYoUzUFmYFkq_ST11A01YJE',
    appId: '1:692445282265:ios:08cfdb2301bf5ce84f63c8',
    messagingSenderId: '692445282265',
    projectId: 'caramel-caster-466105-n4',
    databaseURL: 'https://caramel-caster-466105-n4-default-rtdb.firebaseio.com',
    storageBucket: 'caramel-caster-466105-n4.firebasestorage.app',
    iosBundleId: 'com.example.aitesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjgHFZiLSIYoUzUFmYFkq_ST11A01YJE',
    appId: '1:692445282265:ios:08cfdb2301bf5ce84f63c8',
    messagingSenderId: '692445282265',
    projectId: 'caramel-caster-466105-n4',
    databaseURL: 'https://caramel-caster-466105-n4-default-rtdb.firebaseio.com',
    storageBucket: 'caramel-caster-466105-n4.firebasestorage.app',
    iosBundleId: 'com.example.aitesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTQ4zutajxiVHKwq1tUzP01zlK4lzJ6LE',
    appId: '1:692445282265:web:cf4aab1122b03fdc4f63c8',
    messagingSenderId: '692445282265',
    projectId: 'caramel-caster-466105-n4',
    authDomain: 'caramel-caster-466105-n4.firebaseapp.com',
    databaseURL: 'https://caramel-caster-466105-n4-default-rtdb.firebaseio.com',
    storageBucket: 'caramel-caster-466105-n4.firebasestorage.app',
    measurementId: 'G-LW4LY5Z7ME',
  );
}
